name = "HypothesisTestsExtra"
uuid = "ddd859b9-8813-4e20-ab59-a7b08a106634"
version = "0.1.0"
authors = ["songtaogui<songtaogui@sina.com>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rmath = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "1.8.1"
Distributions = "0.25.123"
FreqTables = "1.0.0"
HypothesisTests = "0.11.6"
LinearAlgebra = "1.12.0"
NamedArrays = "0.10.5"
PrettyTables = "3.1.2"
Printf = "1.11.0"
Random = "1.11.0"
Reexport = "1.2.2"
Rmath = "0.9.0"
SpecialFunctions = "2.6.1"
Statistics = "1.11.1"
StatsAPI = "1.8.0"
Test = "1.11.0"
julia = "1.12"
